# Generated by Django 4.0.4 on 2022-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_node_type', models.CharField(choices=[('House', 'house'), ('Person', 'house'), ('Vehicle', 'house')], max_length=20, verbose_name='first node type')),
                ('first_node_id', models.IntegerField(verbose_name='first node id')),
                ('second_node_type', models.CharField(choices=[('House', 'house'), ('Person', 'house'), ('Vehicle', 'house')], max_length=20, verbose_name='second node type')),
                ('second_node_id', models.IntegerField(verbose_name='second node id')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
            },
        ),
    ]
