# Generated by Django 4.0.4 on 2022-08-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_relation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='first_node_id',
            field=models.CharField(max_length=255, verbose_name='first node id'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='first_node_type',
            field=models.CharField(choices=[('House', 'house'), ('Person', 'person'), ('Vehicle', 'vehicle')], max_length=20, verbose_name='first node type'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='second_node_id',
            field=models.CharField(max_length=255, verbose_name='second node id'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='second_node_type',
            field=models.CharField(choices=[('House', 'house'), ('Person', 'person'), ('Vehicle', 'vehicle')], max_length=20, verbose_name='second node type'),
        ),
    ]
