# Generated by Django 4.0.4 on 2022-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_relation_first_node_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
