# Generated by Django 4.1 on 2022-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.CharField(max_length=16, unique=True, verbose_name='post_number')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('area', models.IntegerField(null=True, verbose_name='area')),
                ('price', models.IntegerField(null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='phone_number')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='national_id')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_id', models.CharField(max_length=20, unique=True, verbose_name='manufacture_id')),
                ('price', models.IntegerField(null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
    ]
