# Generated by Django 4.0.4 on 2022-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_relation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='filename',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='filename'),
        ),
    ]
