# Generated by Django 4.0.4 on 2022-10-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dataset_remove_relation_filename_relation_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=255, null=True, verbose_name='node type')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
            ],
        ),
    ]
