# Generated by Django 4.0.4 on 2022-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_nodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeimage',
            name='node_type',
            field=models.CharField(choices=[('House', 'house'), ('Person', 'person'), ('Vehicle', 'vehicle')], max_length=255, null=True, verbose_name='node type'),
        ),
    ]
