# Generated by Django 4.0.4 on 2022-12-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_nodeimage_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('first_node_type', models.CharField(choices=[('House', 'house'), ('Person', 'person'), ('Vehicle', 'vehicle')], max_length=20, verbose_name='first node type')),
                ('second_node_type', models.CharField(choices=[('House', 'house'), ('Person', 'person'), ('Vehicle', 'vehicle')], max_length=20, verbose_name='second node type')),
                ('min_relations', models.PositiveIntegerField(default=0)),
                ('max_relations', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
