# Generated by Django 4.0.4 on 2022-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeCustomFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('node_type', models.CharField(choices=[('House', 'house'), ('Person', 'person'), ('Vehicle', 'vehicle')], max_length=20, verbose_name='node type')),
                ('field_name', models.CharField(max_length=255, verbose_name='field name')),
                ('min_value', models.PositiveIntegerField(default=0)),
                ('max_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customfilter',
            name='max_relations',
            field=models.PositiveIntegerField(),
        ),
    ]
